# .github/workflows/android-debug.yml
name: Android Debug APK

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show workspace layout (debug)
        run: |
          pwd
          ls -la
          echo "---------- app ----------"
          ls -la app || true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # (Opcional) Instalar/aceptar licencias y herramientas concretas
      - name: Accept SDK licenses & install build tools
        shell: bash
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Assemble Debug
        run: ./gradlew --no-daemon clean :app:assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-${{ github.sha }}
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
